### ISSUE TITLE
do we reference the aws platform guide in flight deck read me?

### ISSUE THREAD

**Issue by VictoriaGuido** [thoughtbot/flightdeck#178]
When I read the read me I expected to see a link to our aws platform guide documentation in confluence. Did I miss it or is there a reason it's not added, or if we should add it where do we think it should go?

**Comment by jferris** [comment]
You're right; I don't think it's currently referenced. We should add a link to the README for sure.

**Comment by clarissalimab** [comment]
The guide is properly referenced now!
